Exit if build fails on publish.

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -10,6 +10,11 @@ remote_directory=`config remote_directory`
 echo "Running build script..."
 bin/build
 
+# Exit if build has failed.
+if [ $? -ne 0 ]; then
+  exit 1
+fi
+
 echo "Running audio sync script..."
 bin/sync_audio_files
 
